data: [local_files/pierce_full/train/, local_files/pierce_full/val/]
labels: [pierce, not-pierce]
batch_size: 8
lr: 0.0001
epochs: 60
n_work: 1
optimizer: adam
criterion: crossentropy
lr_step: 100
lr_gamma: 0.1
T_max: 20
label_smoothing: 0.1