data: [local_files/pierce_full/train/, local_files/pierce_full/val/]
batch_size: 16
lr: 0.001
epochs: 100
n_work: 1
optimizer: adam
criterion: crossentropy
lr_step: 30
lr_gamma: 0.1
labels: [not-pierce, pierce]